### ISSUE TITLE
Updater should initialize addressList when no AOBs.xml file is found

### ISSUE THREAD

**Issue by Francesco149** [Waty/WatyBot#39]
Hey, the updater is pretty dam handy (although I don't like CLI).
The only minor issue I've seen so far is that the first time you inject it and try to add an aob it will throw a nullreferenceexception if you do not have an AOBs.xml file already saved. This is easily solved by adding

```
else 
{
    addressList = gcnew List<Address ^>;
}
```

where it checks if the file exists in MyForm::ReadXmlData

**Comment by Waty** [comment]
Thanks for reporting the issue, I'm actually thinking of rewriting this using [nanapro](https://github.com/cnjinhao/nana) instead of CLI if I'm bored at school tomorrow :-P
